# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       upower

# >> macros
# << macros

Summary:    Power Management Service
Version:    0.99.0
Release:    1
Group:      System/Libraries
License:    GPLv2+
URL:        http://upower.freedesktop.org/
Source0:    %{name}-%{version}.tar.xz
Source100:  upower.yaml
Patch0:     0001-lib-Fix-segfault-on-getting-property-when-daemon-is-.patch
Requires:   polkit >= 0.92
Requires:   udev
Requires:   pm-utils >= 1.2.2.1
Requires:   gobject-introspection
Requires(preun): systemd
Requires(post): systemd
Requires(post): /sbin/ldconfig
Requires(postun): systemd
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(gudev-1.0) >= 147
BuildRequires:  pkgconfig(libusb-1.0) >= 1.0.0
BuildRequires:  pkgconfig(dbus-1) >= 1.0
BuildRequires:  pkgconfig(dbus-glib-1) >= 0.76
BuildRequires:  pkgconfig(glib-2.0) >= 2.21.5
BuildRequires:  pkgconfig(gio-2.0) >= 2.16.1
BuildRequires:  pkgconfig(polkit-gobject-1) >= 0.97
BuildRequires:  pkgconfig(udev) >= 187
BuildRequires:  pkgconfig(systemd)
BuildRequires:  pkgconfig(gtk-doc)
BuildRequires:  libtool
BuildRequires:  intltool
BuildRequires:  gettext
BuildRequires:  gobject-introspection-devel

%description
UPower (formerly DeviceKit-power) provides a daemon, API and command
line tools for managing power devices attached to the system.


%package devel
Summary:    Headers and libraries for UPower
Group:      Development/System
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains the files necessary to develop applications |
that use UPower.


%prep
%setup -q -n %{name}-%{version}/upstream

# 0001-lib-Fix-segfault-on-getting-property-when-daemon-is-.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# Create configure and stuff
NOCONFIGURE=1 ./autogen.sh
# << build pre

%configure --disable-static \
    --disable-gtk-doc \
    --disable-man-pages \
    --enable-introspection

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%find_lang upower

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files -f upower.lang
%defattr(-,root,root,-)
%doc NEWS COPYING AUTHORS HACKING README
%{_libdir}/libupower-glib.so.*
%config %{_sysconfdir}/dbus-1/system.d/*.conf
%{_udevrulesdir}/*.rules
%dir %{_localstatedir}/lib/upower
%dir %{_sysconfdir}/UPower
%config %{_sysconfdir}/UPower/UPower.conf
%{_bindir}/upower
%{_libexecdir}/upowerd
%{_unitdir}/upower.service
%{_datadir}/dbus-1/system-services/*.service
%{_libdir}/girepository-1.0/*.typelib
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_datadir}/dbus-1/interfaces/*.xml
%{_libdir}/libupower-glib.so
%{_libdir}/pkgconfig/*.pc
%dir %{_includedir}/libupower-glib
%{_includedir}/libupower-glib/*.h
%{_datadir}/gir-1.0/*.gir
# >> files devel
# << files devel
